### Signup
### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "buyer_john",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@buyer.com",
  "password": "parola123",
  "role": "buyer"
}


### Create Seller
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "seller_mike",
  "firstName": "Mike",
  "lastName": "Auto",
  "email": "mike@seller.com",
  "password": "parola123",
  "role": "seller"
}