### Signup
### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "buyer_john",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@buyer.com",
  "password": "parola123",
  "role": "buyer"
}


### Create Seller
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
   "username": "seller_mike",
     "firstName": "Mike",
     "lastName": "Auto",
     "email": "mike@seller.com",
     "password": "parola123",
     "role": "seller"
}

### Signin with email
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "john@buyer.com",
  "password": "new_password_456"
}


### forgot password

POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "mike@seller.com"
}

### reset password 
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "resetToken": "bc9f7d360ac1a7050fbb9ddbaabaef458d2036539db07048156245fc59617fbc",
  "newPassword": "new_password_123"
}

### verify email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
  "token": "71f5bc4900cd6ab33ac8d662b08f61d9ce4247006548099b886d3372ae317b80"
}

### resend verification email 
POST http://localhost:3000/auth/resend-verification
Content-Type: application/json

{
  "email": "mike@seller.com"
}


### Logout
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYnV5ZXJfam9obiIsImlhdCI6MTc3MDUwMDM3NywiZXhwIjoxNzcwNTAxMjc3fQ.78_qYAMG8kxlaSmUNQFUC25G2wo6bH-QazK6mtn6lfM


### change password
POST http://localhost:3000/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYnV5ZXJfam9obiIsImlhdCI6MTc3MDUwMDUwOCwiZXhwIjoxNzcwNTAxNDA4fQ.29DM0mt0WVaDHOSoijdckHOCWPmw6nHGY7821C4m0xw
Content-Type: application/json

{
  "currentPassword": "parola123",
  "newPassword": "new_password_456"
}
 
### revoke sessions
POST http://localhost:3000/auth/revoke-sessions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiYnV5ZXJfam9obiIsImlhdCI6MTc3MDUwMTIwMSwiZXhwIjoxNzcwNTAyMTAxfQ.z7i5TAV6Ludler2jgi28oZlniww6HMaSGauDqWxTDFQ

